Q.8 Explain Purpose of Try and Catch block.

Ans: The purpose of the try block in JavaScript is to enclose a section of code where an error might occur. It provides a protected environment for potentially risky code. If an error occurs within the try block, the catch block is triggered.

 The catch block is responsible for catching and handling the error. It allows us to define an error handling routine and specify actions to be taken when an error occurs. The catch block takes an error object as a parameter, which represents the error that occurred. By using try and catch together, we can control the flow of execution and gracefully handle errors, preventing the program from crashing and ensuring proper error management.